# Generated by Django 4.0.4 on 2022-06-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tutorship', '0001_initial'),
        ('UserAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_public', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('author', models.CharField(max_length=50)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserAuthentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceTutorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.resource')),
                ('tutorship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutorship.tutorship')),
            ],
        ),
    ]
