# Generated by Django 4.0.4 on 2022-06-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Region', '0001_initial'),
        ('Session', '0001_initial'),
        ('UserAuthentication', '0001_initial'),
        ('Payment', '0001_initial'),
        ('Modality', '0001_initial'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuthentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='TutorAvailableSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuthentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_person', models.IntegerField(default=0)),
                ('increment_per_half_hour', models.IntegerField(default=0)),
                ('average_rating', models.IntegerField(default=0)),
                ('modality_type', models.ManyToManyField(to='Modality.modality')),
                ('payment_type', models.ManyToManyField(to='Payment.payment')),
                ('region', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Region.regions')),
                ('session_type', models.ManyToManyField(to='Session.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuthentication.user')),
            ],
        ),
    ]
