# Generated by Django 4.0.4 on 2022-06-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0001_initial'),
        ('Modality', '0001_initial'),
        ('Payment', '0001_initial'),
        ('Tutor', '0003_alter_tutor_modality_type_alter_tutor_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='modality_type',
            field=models.ManyToManyField(to='Modality.modality'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='payment_type',
            field=models.ManyToManyField(to='Payment.payment'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='session_type',
            field=models.ManyToManyField(to='Session.session'),
        ),
    ]
